### ISSUE TITLE
能请教下适配了新版的m-team了吗，具体需要怎么用？

### ISSUE THREAD

**Issue by myleo1** [mysll/nts#1]
目前已正常获取cookie，数据统计功能都正常，站点资源无法获取。
求问是操作姿势有误吗？

**Comment by mysll** [comment]
刚去看了一下,站点资源好像出bug了,我修复一下

**Comment by mysll** [comment]
@myleo1 已修复,顺便说一下,m-team已经关闭了cookie,f12抓取不到cookie.如果不需要模拟登录,则cookie里随便写点什么不要留空即可.如果需要模拟登录,则需要站点里取消二次验证,改成使用邮箱接收.然后在站点管理-站点维护,点击站点卡片右上角的更新cookie和ua,输入网站用户名和密码点更新.依次在弹窗中输入邮箱和邮箱验证码,成功后会在cookie里写入验证信息.

**Comment by myleo1** [comment]
@mysll 感谢大佬，测试过暂时未发现问题，又可以愉快地使用m-team了。
